name: Get branch name
on:
  push:
    branches: [main]
jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show branch name
        run: echo "The branch name is $GITHUB_REF"
