name: Get commit ID
on:
  push:
    branches: [main]
jobs:
  get-commit-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show commit ID
        run: echo "The commit ID is $GITHUB_SHA"
