name: Print current date and time
on:
  push:
    branches:
      - main
jobs:
  print-date-time:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date and time
        run: echo "The current date and time is $(date)."
