---
name: Call Workflow in Different Repository
on: null
  workflow_dispatch: null
jobs: null
  call-workflow: null
    runs-on: ubuntu-latest
    steps: null
    - name: Trigger Workflow in Different Repository
      uses: peter-evans/repository-dispatch@v1
      with: null
        repository: patilswati98/demo-2
        token: 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
        event-type: call-my-workflow
        client-payload: '{"my_input_param": "input_value"}'
