name: Trigger Workflow
 
on:
  workflow_dispatch:
 
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: patilswati98/demo-2
          ref: main
 
      - name: Trigger Workflow
        uses: ./.github/workflows/main.yml
